apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    run: more-traffic 
  name: more-traffic 
  namespace: fake-traffic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: more-traffic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: more-traffic 
    spec:
      containers:
      - command: ["/bin/sh"]
        args: ["-c", "while true; do wget frontend.default:3000; sleep 1;done"]
        image: busybox
        name: busybox
        resources: {}
