apiVersion: v1
kind: Pod
metadata:
  name: unschedulable
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: do_not_exist
