apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    config:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      kubelet:
        tlsVerify: false
    apm:
      enabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    process:
      enabled: true
      processCollectionEnabled: true
